const questions = [
  {"ind":"Verbs.","word":" be","correct":"ser/estar","choices":["ter","ir","ser/estar","fazer"],"hint":"estado, identidade ou condição","example":"I am tired"},
  {"ind":"Verbs.","word":" have","correct":"ter","choices":["ser/estar","ter","ir","ver"],"hint":"posse ou obrigação","example":"I have a car"},
  {"ind":"Verbs.","word":" do","correct":"fazer","choices":["ir","fazer","ver","dar"],"hint":"ações em geral","example":"I do my homework"},
  {"ind":"Verbs.","word":" go","correct":"ir","choices":["vir","ficar","ir","andar"],"hint":"movimento","example":"I go to work"},
  {"ind":"Verbs.","word":" say","correct":"dizer","choices":["falar","ouvir","dizer","pedir"],"hint":"expressar palavras","example":"I say the truth"},
  {"ind":"Verbs.","word":" get","correct":"obter/pegar","choices":["dar","levar","obter/pegar","perder"],"hint":"receber ou conseguir","example":"I get a gift"},
  {"ind":"Verbs.","word":" make","correct":"fazer/criar","choices":["comprar","fazer/criar","quebrar","usar"],"hint":"criação ou produção","example":"I make a cake"},
  {"ind":"Verbs.","word":" see","correct":"ver","choices":["olhar","ver","achar","sentir"],"hint":"percepção visual","example":"I see you"},
  {"ind":"Verbs.","word":" come","correct":"vir","choices":["ir","vir","chegar","voltar"],"hint":"movimento em direção","example":"Come here"},
  {"ind":"Verbs.","word":" think","correct":"pensar","choices":["saber","pensar","crer","lembrar"],"hint":"processo mental","example":"I think so"},
  {"ind":"Verbs.","word":" look","correct":"olhar","choices":["ver","olhar","achar","buscar"],"hint":"direcionar os olhos","example":"Look at me"},
  {"ind":"Verbs.","word":" want","correct":"querer","choices":["gostar","querer","precisar","pedir"],"hint":"desejo","example":"I want coffee"},
  {"ind":"Verbs.","word":" give","correct":"dar","choices":["levar","dar","receber","mandar"],"hint":"transferir algo","example":"I give you this"},
  {"ind":"Verbs.","word":" use","correct":"usar","choices":["usar","quebrar","jogar","criar"],"hint":"utilização","example":"I use a computer"},
  {"ind":"Verbs.","word":" find","correct":"encontrar","choices":["perder","buscar","encontrar","ver"],"hint":"descoberta","example":"I find the keys"},
  {"ind":"Verbs.","word":" tell","correct":"contar/dizer","choices":["perguntar","contar/dizer","ouvir","gritar"],"hint":"informar alguém","example":"I tell a story"},
  {"ind":"Verbs.","word":" work","correct":"trabalhar","choices":["estudar","trabalhar","descansar","viajar"],"hint":"atividade profissional","example":"I work here"},
  {"ind":"Verbs.","word":" call","correct":"chamar/ligar","choices":["responder","chamar/ligar","falar","ouvir"],"hint":"comunicação","example":"I call my mom"},
  {"ind":"Verbs.","word":" try","correct":"tentar","choices":["falhar","tentar","conseguir","parar"],"hint":"esforço","example":"I try again"},
  {"ind":"Verbs.","word":" ask","correct":"perguntar","choices":["responder","perguntar","dizer","ouvir"],"hint":"fazer uma pergunta","example":"I ask a question"},
  {"ind":"Verbs.","word":" need","correct":"precisar","choices":["querer","precisar","ter","usar"],"hint":"necessidade","example":"I need help"},
  {"ind":"Verbs.","word":" feel","correct":"sentir","choices":["ver","sentir","pensar","ouvir"],"hint":"emoções ou sentidos","example":"I feel happy"},
  {"ind":"Verbs.","word":" become","correct":"tornar-se","choices":["ficar","tornar-se","ser","parecer"],"hint":"mudança de estado","example":"I become strong"},
  {"ind":"Verbs.","word":" leave","correct":"sair/deixar","choices":["entrar","sair/deixar","ficar","voltar"],"hint":"partida ou abandono","example":"I leave early"},
  {"ind":"Verbs.","word":" put","correct":"colocar","choices":["tirar","colocar","mover","guardar"],"hint":"posicionar algo","example":"I put it here"},
  {"ind":"Verbs.","word":" mean","correct":"significar","choices":["querer","significar","explicar","dizer"],"hint":"ter sentido","example":"What does it mean?"},

  {"ind":"","word":" house","correct":"casa","choices":["carro","porta","casa","rua"],"hint":"Lugar onde as pessoas moram","example":"My house is big."},
  {"ind":"nouns","word":" car","correct":"carro","choices":["carro","bicicleta","ônibus","moto"],"hint":"Veículo com rodas usado para transporte","example":"I have a red car."},
  {"ind":"nouns","word":" door","correct":"porta","choices":["janela","porta","cama","mesa"],"hint":"Entrada ou saída de um cômodo","example":"Close the door."},
  {"ind":"nouns","word":" street","correct":"rua","choices":["rua","praça","avenida","alameda"],"hint":"Via onde carros e pessoas passam","example":"I live on this street."},
  {"ind":"nouns","word":" book","correct":"livro","choices":["caderno","livro","revista","jornal"],"hint":"Objeto com páginas e informações","example":"I am reading a book."},
  {"ind":"nouns","word":" chair","correct":"cadeira","choices":["mesa","cadeira","sofá","poltrona"],"hint":"Lugar para sentar","example":"The chair is comfortable."},
  {"ind":"nouns","word":" window","correct":"janela","choices":["porta","janela","teto","parede"],"hint":"Abertura na parede para luz e ar","example":"Open the window."},
  {"ind":"nouns","word":" table","correct":"mesa","choices":["mesa","cadeira","sofá","armário"],"hint":"Móvel usado para apoiar objetos","example":"Put the book on the table."},
  {"ind":"nouns","word":" bed","correct":"cama","choices":["cama","sofá","cadeira","tapete"],"hint":"Lugar para dormir","example":"I sleep on my bed."},
  {"ind":"nouns","word":" cat","correct":"gato","choices":["cachorro","gato","pássaro","coelho"],"hint":"Animal doméstico que mia","example":"The cat is black."},
  {"ind":"nouns","word":" dog","correct":"cachorro","choices":["cachorro","gato","peixe","pássaro"],"hint":"Animal doméstico que late","example":"My dog is friendly."},
  {"ind":"nouns","word":" bird","correct":"pássaro","choices":["gato","cachorro","pássaro","peixe"],"hint":"Animal que voa e canta","example":"The bird is singing."},
  {"ind":"nouns","word":" fish","correct":"peixe","choices":["peixe","gato","cachorro","pássaro"],"hint":"Animal que vive na água","example":"I caught a fish."},
  {"ind":"nouns","word":" milk","correct":"leite","choices":["água","leite","suco","chá"],"hint":"Bebida branca de vaca","example":"I drink milk every morning."},
  {"ind":"nouns","word":" water","correct":"água","choices":["água","leite","suco","chá"],"hint":"Bebida essencial para viver","example":"I need water."},
  {"ind":"nouns","word":" juice","correct":"suco","choices":["leite","água","suco","chá"],"hint":"Bebida de frutas","example":"I like orange juice."},
  {"ind":"nouns","word":" coffee","correct":"café","choices":["chá","café","leite","suco"],"hint":"Bebida quente feita com grãos","example":"I drink coffee in the morning."},
  {"ind":"nouns","word":" tea","correct":"chá","choices":["chá","café","leite","suco"],"hint":"Bebida feita com folhas","example":"I like green tea."},
  {"ind":"nouns","word":" school","correct":"escola","choices":["escola","hospital","igreja","loja"],"hint":"Lugar onde se aprende","example":"Children go to school."},
  {"ind":"nouns","word":" hospital","correct":"hospital","choices":["hospital","escola","loja","igreja"],"hint":"Lugar para tratar doentes","example":"He is in the hospital."},
  {"ind":"nouns","word":" store","correct":"loja","choices":["loja","mercado","shopping","supermercado"],"hint":"Lugar para comprar produtos","example":"I bought shoes at the store."},
  {"ind":"nouns","word":" church","correct":"igreja","choices":["igreja","templo","escola","hospital"],"hint":"Lugar de culto religioso","example":"They go to church on Sunday."},
  {"ind":"nouns","word":" carrot","correct":"cenoura","choices":["batata","cenoura","tomate","cebola"],"hint":"Vegetal laranja e saudável","example":"I eat a carrot every day."},
  {"ind":"nouns","word":" potato","correct":"batata","choices":["batata","cenoura","tomate","alface"],"hint":"Vegetal usado em várias comidas","example":"I like mashed potato."},

  {"ind":"Adjectives.","word":" big","correct":"grande","choices":["pequeno","longo","grande","curto"],"hint":"Algo de tamanho maior que o normal","example":"The house is big."},
  {"ind":"Adjectives.","word":" small","correct":"pequeno","choices":["pequeno","grande","alto","baixo"],"hint":"Algo de tamanho menor que o normal","example":"She has a small dog."},
  {"ind":"Adjectives.","word":" long","correct":"longo","choices":["curto","longo","rápido","devagar"],"hint":"Algo que se estende bastante","example":"He has long hair."},
  {"ind":"Adjectives.","word":" short","correct":"curto","choices":["curto","longo","alto","baixo"],"hint":"Algo que não é longo","example":"The meeting was short."},
  {"ind":"Adjectives.","word":" tall","correct":"alto","choices":["baixo","alto","pequeno","grande"],"hint":"De grande altura","example":"He is very tall."},
  {"ind":"Adjectives.","word":" low","correct":"baixo","choices":["alto","baixo","pequeno","longo"],"hint":"De pouca altura ou posição inferior","example":"The shelf is low."},
  {"ind":"Adjectives.","word":" fast","correct":"rápido","choices":["rápido","devagar","lento","forte"],"hint":"Algo que se move rapidamente","example":"She runs fast."},
  {"ind":"Adjectives.","word":" slow","correct":"devagar","choices":["rápido","lento","devagar","forte"],"hint":"Algo que se move ou acontece devagar","example":"The car is slow."},
  {"ind":"Adjectives.","word":" hot","correct":"quente","choices":["frio","quente","morno","gelado"],"hint":"De alta temperatura","example":"The soup is hot."},
  {"ind":"Adjectives.","word":" cold","correct":"frio","choices":["quente","frio","gelado","moreno"],"hint":"De baixa temperatura","example":"The water is cold."},
  {"ind":"Adjectives.","word":" warm","correct":"morno","choices":["quente","frio","morno","gelado"],"hint":"Temperatura agradável, nem quente nem fria","example":"I like warm tea."},
  {"ind":"Adjectives.","word":" strong","correct":"forte","choices":["fraco","forte","frágil","pequeno"],"hint":"Com muita força","example":"He is strong."},
  {"ind":"Adjectives.","word":" weak","correct":"fraco","choices":["forte","fraco","grande","pequeno"],"hint":"Com pouca força","example":"The bridge is weak."},
  {"ind":"Adjectives.","word":" happy","correct":"feliz","choices":["triste","feliz","bravo","cansado"],"hint":"Sentindo alegria","example":"She is happy today."},
  {"ind":"Adjectives.","word":" sad","correct":"triste","choices":["feliz","triste","cansado","alegre"],"hint":"Sentindo tristeza","example":"He looks sad."},
  {"ind":"Adjectives.","word":" angry","correct":"bravo","choices":["feliz","triste","bravo","alegre"],"hint":"Sentindo raiva","example":"She is angry."},
  {"ind":"Adjectives.","word":" tired","correct":"cansado","choices":["cansado","feliz","bravo","triste"],"hint":"Precisando descansar","example":"I am tired."},
  {"ind":"Adjectives.","word":" beautiful","correct":"bonito","choices":["bonito","feio","grande","pequeno"],"hint":"Que agrada aos olhos","example":"The garden is beautiful."},
  {"ind":"Adjectives.","word":" ugly","correct":"feio","choices":["bonito","feio","grande","pequeno"],"hint":"Que não agrada aos olhos","example":"The painting is ugly."},
  {"ind":"Adjectives.","word":" young","correct":"jovem","choices":["velho","jovem","novo","antigo"],"hint":"Com pouca idade","example":"My brother is young."},
  {"ind":"Adjectives.","word":" old","correct":"velho","choices":["velho","novo","jovem","antigo"],"hint":"Com muita idade","example":"The man is old."},
  {"ind":"Adjectives.","word":" new","correct":"novo","choices":["novo","velho","jovem","antigo"],"hint":"Recém-criado ou adquirido","example":"I bought a new car."},
  {"ind":"Adjectives.","word":" heavy","correct":"pesado","choices":["leve","pesado","grande","forte"],"hint":"Com muito peso","example":"This box is heavy."},
  {"ind":"Adjectives.","word":" light","correct":"leve","choices":["leve","pesado","forte","fraco"],"hint":"Com pouco peso","example":"The bag is light."},
  {"ind":"Adjectives.","word":" clean","correct":"limpo","choices":["sujo","limpo","grande","pequeno"],"hint":"Sem sujeira","example":"The room is clean."},
  {"ind":"Adjectives.","word":" dirty","correct":"sujo","choices":["sujo","limpo","grande","pequeno"],"hint":"Com sujeira","example":"His shoes are dirty."},

  {"ind":"Articles.","word":" a","correct":"um/uma","choices":["o/a","um/uma","e","mas"],"hint":"Usado antes de palavras singulares que começam com consoante","example":"I have a dog."},
  {"ind":"Articles.","word":" an","correct":"um/uma","choices":["o/a","um/uma","e","mas"],"hint":"Usado antes de palavras singulares que começam com vogal","example":"She is an engineer."},
  {"ind":"Articles.","word":" the","correct":"o/a/os/as","choices":["o/a/os/as","um/uma","e","mas"],"hint":"Usado para algo específico","example":"The book is on the table."},
  {"ind":"Articles.","word":" some","correct":"algum/alguns/algumas","choices":["nenhum","algum/alguns/algumas","o/a","um/uma"],"hint":"Usado para plural ou quantidades indefinidas","example":"I bought some apples."},
  {"ind":"Articles.","word":" any","correct":"algum/nenhum","choices":["algum/nenhum","um/uma","o/a","e"],"hint":"Usado em frases negativas ou perguntas","example":"Do you have any money?"},
  {"ind":"Articles.","word":" no","correct":"nenhum","choices":["nenhum","algum","o/a","um/uma"],"hint":"Indica ausência de algo","example":"There is no milk."},
  {"ind":"Articles.","word":" each","correct":"cada","choices":["cada","todo","algum","nenhum"],"hint":"Indica individualidade em grupo","example":"Each student has a book."},
  {"ind":"Articles.","word":" every","correct":"todo","choices":["cada","todo","algum","nenhum"],"hint":"Indica totalidade em grupo","example":"Every child loves candy."},
  {"ind":"Articles.","word":" either","correct":"um dos dois","choices":["nenhum","um dos dois","todos","cada"],"hint":"Escolha entre dois itens","example":"You can take either road."},
  {"ind":"Articles.","word":" neither","correct":"nenhum dos dois","choices":["nenhum dos dois","um dos dois","todos","cada"],"hint":"Negativa para dois itens","example":"Neither answer is correct."},
  {"ind":"Articles.","word":" both","correct":"ambos","choices":["nenhum","ambos","cada","um dos dois"],"hint":"Refere-se a dois itens juntos","example":"Both friends are here."},
  {"ind":"Articles.","word":" plenty of","correct":"muito/muita/muitos/muitas","choices":["pouco","muito/muita/muitos/muitas","algum","nenhum"],"hint":"Grande quantidade","example":"There is plenty of food."},
  {"ind":"Articles.","word":" a lot of","correct":"muito/muita/muitos/muitas","choices":["pouco","muito/muita/muitos/muitas","nenhum","algum"],"hint":"Grande quantidade, informal","example":"I have a lot of friends."},
  {"ind":"Articles.","word":" few","correct":"poucos/poucas","choices":["poucos/poucas","muitos/muitas","alguns","nenhum"],"hint":"Pequena quantidade, contável","example":"Few people attended the meeting."},
  {"ind":"Articles.","word":" a few","correct":"alguns/algumas","choices":["alguns/algumas","poucos/poucas","muitos/muitas","nenhum"],"hint":"Pequena quantidade positiva","example":"I have a few books."},
  {"ind":"Articles.","word":" little","correct":"pouco/pouca","choices":["pouco/pouca","muito/muita","nenhum","algum"],"hint":"Pequena quantidade, incontável","example":"There is little water."},
  {"ind":"Articles.","word":" a little","correct":"um pouco de","choices":["um pouco de","pouco/pouca","muito/muita","nenhum"],"hint":"Pequena quantidade positiva, incontável","example":"I have a little money."},
  {"ind":"Articles.","word":" the same","correct":"o mesmo / a mesma","choices":["o mesmo / a mesma","diferente","algum","nenhum"],"hint":"Indica identidade","example":"We have the same car."},
  {"ind":"Articles.","word":" such","correct":"tal / tais","choices":["tal / tais","um/uma","nenhum","o/a"],"hint":"Indica tipo ou característica","example":"She is such a nice person."},
  {"ind":"Articles.","word":" another","correct":"outro / outra","choices":["outro / outra","mesmo","um/uma","nenhum"],"hint":"Mais um adicional","example":"I want another cup of coffee."},
  {"ind":"Articles.","word":" other","correct":"outros / outras","choices":["outros / outras","mesmo","um/uma","nenhum"],"hint":"Diferentes de um grupo","example":"Other students are waiting."},
  {"ind":"Articles.","word":" this","correct":"este / esta","choices":["este / esta","esse / essa","aquele / aquela","um/uma"],"hint":"Próximo no espaço ou tempo","example":"This is my house."},
  {"ind":"Articles.","word":" that","correct":"aquele / aquela","choices":["este / esta","aquele / aquela","esse / essa","um/uma"],"hint":"Distante no espaço ou tempo","example":"That is a beautiful painting."},
  {"ind":"Articles.","word":" these","correct":"estes / estas","choices":["estes / estas","esses / essas","aqueles / aquelas","um/uma"],"hint":"Próximos e plurais","example":"These are my friends."},

  {"ind":"Conjunctions.","word":" and","correct":"e","choices":["ou","mas","e","porque"],"hint":"Usada para adicionar informações","example":"I like apples and oranges."},
  {"ind":"Conjunctions.","word":" but","correct":"mas","choices":["e","ou","mas","porque"],"hint":"Usada para mostrar contraste","example":"I like coffee, but I don't like tea."},
  {"ind":"Conjunctions.","word":" or","correct":"ou","choices":["e","ou","mas","porque"],"hint":"Usada para indicar escolha","example":"Do you want tea or coffee?"},
  {"ind":"Conjunctions.","word":" because","correct":"porque","choices":["porque","mas","ou","e"],"hint":"Usada para dar motivo ou razão","example":"I stayed home because it was raining."},
  {"ind":"Conjunctions.","word":" so","correct":"então / por isso","choices":["e","mas","so","ou"],"hint":"Usada para mostrar consequência","example":"It was raining, so we stayed home."},
  {"ind":"Conjunctions.","word":" yet","correct":"ainda / porém","choices":["porque","yet","e","ou"],"hint":"Usada para contraste ou surpresa","example":"He is rich, yet unhappy."},
  {"ind":"Conjunctions.","word":" for","correct":"pois / porque","choices":["for","mas","e","ou"],"hint":"Usada para explicar motivo formal","example":"I stayed home, for it was raining."},
  {"ind":"Conjunctions.","word":" nor","correct":"nem","choices":["nem","ou","mas","porque"],"hint":"Usada para negar duas ideias juntas","example":"He neither smiles nor talks."},
  {"ind":"Conjunctions.","word":" either…or","correct":"ou…ou","choices":["ou…ou","nem…nem","e…e","mas…mas"],"hint":"Escolha entre duas opções","example":"You can either stay or go."},
  {"ind":"Conjunctions.","word":" neither…nor","correct":"nem…nem","choices":["ou…ou","nem…nem","e…e","mas…mas"],"hint":"Negação dupla","example":"I like neither coffee nor tea."},
  {"ind":"Conjunctions.","word":" although","correct":"embora","choices":["porque","embora","e","ou"],"hint":"Introduz contraste ou concessão","example":"Although it was raining, we went out."},
  {"ind":"Conjunctions.","word":" though","correct":"embora / porém","choices":["embora","porque","e","ou"],"hint":"Semelhante a although, usado em contraste","example":"I like him, though he is rude."},
  {"ind":"Conjunctions.","word":" if","correct":"se","choices":["se","porque","mas","e"],"hint":"Introduz condição","example":"I will go if it stops raining."},
  {"ind":"Conjunctions.","word":" unless","correct":"a menos que","choices":["a menos que","se","mas","ou"],"hint":"Introduz exceção ou condição negativa","example":"I won’t go unless you come."},
  {"ind":"Conjunctions.","word":" when","correct":"quando","choices":["quando","onde","como","por que"],"hint":"Indica tempo ou ocasião","example":"Call me when you arrive."},
  {"ind":"Conjunctions.","word":" while","correct":"enquanto","choices":["enquanto","porque","mas","ou"],"hint":"Indica simultaneidade ou contraste","example":"I read while she cooked."},
  {"ind":"Conjunctions.","word":" as","correct":"como / enquanto","choices":["como / enquanto","porque","mas","ou"],"hint":"Indica causa ou tempo","example":"As it was raining, we stayed home."},
  {"ind":"Conjunctions.","word":" since","correct":"já que / desde que","choices":["já que / desde que","mas","e","ou"],"hint":"Indica causa ou tempo passado","example":"Since you are here, let's start."},
  {"ind":"Conjunctions.","word":" after","correct":"depois que","choices":["antes que","depois que","quando","enquanto"],"hint":"Indica sequência no tempo","example":"I went out after I finished work."},
  {"ind":"Conjunctions.","word":" before","correct":"antes que","choices":["antes que","depois que","quando","enquanto"],"hint":"Indica antecedência no tempo","example":"Wash your hands before you eat."},
  {"ind":"Conjunctions.","word":" as soon as","correct":"assim que","choices":["assim que","antes que","quando","enquanto"],"hint":"Indica imediata sequência","example":"I called her as soon as I arrived."},
  {"ind":"Conjunctions.","word":" even though","correct":"mesmo que / embora","choices":["mesmo que / embora","porque","e","ou"],"hint":"Indica contraste forte","example":"Even though it was raining, we went out."},
  {"ind":"Conjunctions.","word":" whether","correct":"se","choices":["se","porque","mas","ou"],"hint":"Indica alternativa ou dúvida","example":"I don’t know whether to go."},
  {"ind":"Conjunctions.","word":" provided that","correct":"desde que","choices":["desde que","mesmo que","e","ou"],"hint":"Indica condição","example":"You can go provided that you finish work."},

  {"ind":"Prepositions.","word":" in","correct":"em","choices":["em","sobre","para","com"],"hint":"Indica lugar dentro de algo ou tempo (mês, ano, século)","example":"I live in Brazil."},
  {"ind":"Prepositions.","word":" on","correct":"sobre / em","choices":["em","sobre / em","para","com"],"hint":"Indica posição em superfície ou dia da semana","example":"The book is on the table."},
  {"ind":"Prepositions.","word":" at","correct":"em / no / na","choices":["em / no / na","sobre","para","com"],"hint":"Indica lugar específico ou horário","example":"I am at the station."},
  {"ind":"Prepositions.","word":" to","correct":"para / a","choices":["em","sobre","para / a","com"],"hint":"Indica direção ou destino","example":"I am going to school."},
  {"ind":"Prepositions.","word":" from","correct":"de / do / da","choices":["de / do / da","para","sobre","com"],"hint":"Indica origem","example":"I am from Brazil."},
  {"ind":"Prepositions.","word":" with","correct":"com","choices":["em","sobre","para","com"],"hint":"Indica companhia ou instrumento","example":"I go to school with my friend."},
  {"ind":"Prepositions.","word":" about","correct":"sobre / acerca de","choices":["sobre / acerca de","para","com","em"],"hint":"Indica assunto ou tema","example":"We talked about the movie."},
  {"ind":"Prepositions.","word":" for","correct":"para / por","choices":["em","para / por","com","sobre"],"hint":"Indica propósito, destinatário ou tempo","example":"This gift is for you."},
  {"ind":"Prepositions.","word":" of","correct":"de","choices":["de","para","em","com"],"hint":"Indica posse, material ou relação","example":"The cover of the book is red."},
  {"ind":"Prepositions.","word":" by","correct":"por / de","choices":["por / de","em","para","com"],"hint":"Indica agente ou meio","example":"This book was written by John."},
  {"ind":"Prepositions.","word":" between","correct":"entre","choices":["entre","com","sobre","para"],"hint":"Indica posição ou relação entre dois elementos","example":"The ball is between the chairs."},
  {"ind":"Prepositions.","word":" among","correct":"entre / no meio de","choices":["entre / no meio de","com","sobre","para"],"hint":"Indica posição dentro de um grupo","example":"She is among friends."},
  {"ind":"Prepositions.","word":" over","correct":"sobre / acima de","choices":["sobre / acima de","em","para","com"],"hint":"Indica movimento ou posição acima","example":"The lamp hangs over the table."},
  {"ind":"Prepositions.","word":" under","correct":"sob / debaixo de","choices":["sob / debaixo de","sobre","em","para"],"hint":"Indica posição abaixo","example":"The shoes are under the bed."},
  {"ind":"Prepositions.","word":" next to","correct":"ao lado de","choices":["ao lado de","em","sobre","para"],"hint":"Indica proximidade lateral","example":"The bank is next to the supermarket."},
  {"ind":"Prepositions.","word":" behind","correct":"atrás de","choices":["atrás de","em frente a","sobre","para"],"hint":"Indica posição posterior","example":"The cat is behind the door."},
  {"ind":"Prepositions.","word":" in front of","correct":"em frente de","choices":["em frente de","atrás de","sobre","para"],"hint":"Indica posição à frente","example":"He is in front of the house."},
  {"ind":"Prepositions.","word":" inside","correct":"dentro de","choices":["dentro de","fora de","sobre","para"],"hint":"Indica interior","example":"The keys are inside the bag."},
  {"ind":"Prepositions.","word":" outside","correct":"fora de","choices":["fora de","dentro de","sobre","para"],"hint":"Indica exterior","example":"The children are playing outside."},
  {"ind":"Prepositions.","word":" through","correct":"através de / por","choices":["através de / por","em","para","com"],"hint":"Indica movimento dentro ou por algo","example":"We walked through the park."},
  {"ind":"Prepositions.","word":" across","correct":"através de / do outro lado","choices":["através de / do outro lado","em","sobre","para"],"hint":"Indica movimento de um lado ao outro","example":"He ran across the street."},
  {"ind":"Prepositions.","word":" along","correct":"ao longo de","choices":["ao longo de","atrás de","sobre","para"],"hint":"Indica movimento ou posição em extensão","example":"We walked along the river."},
  {"ind":"Prepositions.","word":" near","correct":"perto de","choices":["perto de","longe de","sobre","para"],"hint":"Indica proximidade","example":"The school is near the park"},
  {"ind":"Prepositions.","word":" at the end of","correct":"no final de","choices":["no final de","no começo de","sobre","para"],"hint":"Indica posição final","example":"The shop is at the end of the street."},
  {"ind":"Prepositions.","word":" opposite","correct":"em frente de / oposto a","choices":["em frente de / oposto a","ao lado de","sobre","para"],"hint":"Indica posição contrária ou frente a","example":"The bank is opposite the school."},

  {"ind":"pronouns","word":" I","correct":"eu","choices":["tu","ele","eu","nós"],"hint":"Usado pelo falante para se referir a si mesmo","example":"I am happy."},
  {"ind":"pronouns","word":" you","correct":"tu / você","choices":["ele","ela","tu / você","nós"],"hint":"Usado para se referir à pessoa com quem se fala","example":"You are kind."},
  {"ind":"pronouns","word":" he","correct":"ele","choices":["ele","ela","eu","nós"],"hint":"Usado para se referir a um homem ou menino","example":"He is tall."},
  {"ind":"pronouns","word":" she","correct":"ela","choices":["ele","ela","eu","nós"],"hint":"Usado para se referir a uma mulher ou menina","example":"She is smart."},
  {"ind":"pronouns","word":" it","correct":"ele / ela (objeto ou animal)","choices":["ele / ela (objeto ou animal)","ele","ela","tu"],"hint":"Usado para objetos, animais ou ideias","example":"It is raining."},
  {"ind":"pronouns","word":" we","correct":"nós","choices":["nós","eles","elas","tu"],"hint":"Usado pelo falante e outra(s) pessoa(s)","example":"We are friends."},
  {"ind":"pronouns","word":" they","correct":"eles / elas","choices":["eles / elas","nós","tu","eu"],"hint":"Usado para falar de várias pessoas ou coisas","example":"They are happy."},
  {"ind":"pronouns","word":" me","correct":"mim / me","choices":["me / mim","eu","tu","ele"],"hint":"Usado como objeto da ação","example":"He called me."},
  {"ind":"pronouns","word":" you (object)","correct":"ti / você / te","choices":["tu / você / te","eu","ele","nós"],"hint":"Objeto da ação, se refere a quem se fala","example":"I saw you."},
  {"ind":"pronouns","word":" him","correct":"lhe / o / ele","choices":["ele / o / lhe","eu","tu","nós"],"hint":"Objeto masculino","example":"I met him yesterday."},
  {"ind":"pronouns","word":" her","correct":"lhe / a / ela","choices":["ela / a / lhe","ele","eu","tu"],"hint":"Objeto feminino","example":"I called her."},
  {"ind":"pronouns","word":" it (object)","correct":"o / a / isso","choices":["o / a / isso","ele","ela","nós"],"hint":"Objeto ou coisa","example":"I found it."},
  {"ind":"pronouns","word":" us","correct":"nos / a nós","choices":["nos / a nós","eles","tu","eu"],"hint":"Objeto plural incluindo o falante","example":"They helped us."},
  {"ind":"pronouns","word":" them","correct":"os / as / lhes","choices":["os / as / lhes","nós","eu","tu"],"hint":"Objeto plural, masculino ou feminino","example":"I saw them."},
  {"ind":"pronouns","word":" my","correct":"meu / minha","choices":["meu / minha","teu / tua","dele / dela","nosso / nossa"],"hint":"Posse do falante","example":"This is my book."},
  {"ind":"pronouns","word":" your","correct":"teu / sua / seu","choices":["teu / sua / seu","meu / minha","dele / dela","nosso / nossa"],"hint":"Posse de quem se fala","example":"Is this your bag?."}, 
  {"ind":"pronouns","word":" his","correct":"dele","choices":["dele","dela","meu / minha","nosso / nossa"],"hint":"Posse de um homem","example":"This is his car."},
  {"ind":"pronouns","word":" her (possessive)","correct":"dela","choices":["dela","dele","meu / minha","nosso / nossa"],"hint":"Posse de uma mulher","example":"That is her house."},
  {"ind":"pronouns","word":" its (possessive)","correct":"dele / dela (coisa / animal)","choices":["dele / dela (coisa / animal)","dele","dela","nosso / nossa"],"hint":"Posse de objeto ou animal","example":"The cat licked its paw."},
  {"ind":"pronouns","word":" our","correct":"nosso / nossa","choices":["nosso / nossa","meu / minha","teu / tua","dele / dela"],"hint":"Posse do falante e outros","example":"This is our school."},
  {"ind":"pronouns","word":" your (plural)","correct":"vosso / sua / suas","choices":["vosso / sua / suas","meu / minha","dele / dela","nosso / nossa"],"hint":"Posse de quem se fala, plural","example":"Is this your house?."}, 
  {"ind":"pronouns","word":" their","correct":"deles / delas","choices":["deles / delas","meu / minha","nosso / nossa","teu / tua"],"hint":"Posse de outras pessoas","example":"Their car is new."},
  {"ind":"pronouns","word":" oneself","correct":"si mesmo / si própria","choices":["si mesmo / si própria","me","te","nos"],"hint":"Reflexivo para enfatizar a própria pessoa","example":"He did it himself."},
  {"ind":"pronouns","word":" myself","correct":"eu mesmo / a mim mesmo","choices":["eu mesmo / a mim mesmo","me","tu","ele"],"hint":"Reflexivo do falante","example":"I made it myself."},
  
  {"ind":"Subject, linking verb, complement.","word":" I eat apples","correct":"Eu como maçãs","choices":["Eu como bananas","Eu como maçãs","Eu leio livros","Eu bebo água"],"hint":"Sujeito + verbo + objeto direto","example":"I eat apples."},
  {"ind":"Subject, linking verb, complement.","word":" She reads books","correct":"Ela lê livros","choices":["Ela escreve cartas","Ela lê livros","Ela assiste TV","Ela come frutas"],"hint":"Sujeito + verbo + objeto direto","example":"She reads books."},
  {"ind":"Subject, linking verb, complement.","word":" He plays football","correct":"Ele joga futebol","choices":["Ele canta músicas","Ele joga futebol","Ele lê jornais","Ele bebe água"],"hint":"Sujeito + verbo + objeto direto","example":"He plays football."},
  {"ind":"Subject, linking verb, complement.","word":" We drink water","correct":"Nós bebemos água","choices":["Nós comemos pão","Nós bebemos água","Nós corremos rápido","Nós lemos livros"],"hint":"Sujeito + verbo + objeto direto","example":"We drink water."},
  {"ind":"Subject, linking verb, complement.","word":" They watch TV","correct":"Eles assistem TV","choices":["Eles jogam cartas","Eles assistem TV","Eles leem livros","Eles bebem suco"],"hint":"Sujeito + verbo + objeto direto","example":"They watch TV."},
  {"ind":"Subject, linking verb, complement.","word":" I write letters","correct":"Eu escrevo cartas","choices":["Eu escrevo cartas","Eu leio revistas","Eu corro rápido","Eu canto músicas"],"hint":"Sujeito + verbo + objeto direto","example":"I write letters."},
  {"ind":"Subject, linking verb, complement.","word":" She drinks milk","correct":"Ela bebe leite","choices":["Ela bebe água","Ela bebe leite","Ela come pão","Ela lê jornais"],"hint":"Sujeito + verbo + objeto direto","example":"She drinks milk."},
  {"ind":"Subject, linking verb, complement.","word":" He reads newspapers","correct":"Ele lê jornais","choices":["Ele lê jornais","Ele escreve cartas","Ele assiste TV","Ele joga futebol"],"hint":"Sujeito + verbo + objeto direto","example":"He reads newspapers."},
  {"ind":"Subject, linking verb, complement.","word":" We play games","correct":"Nós jogamos jogos","choices":["Nós jogamos jogos","Nós bebemos suco","Nós corremos no parque","Nós lemos livros"],"hint":"Sujeito + verbo + objeto direto","example":"We play games."},
  {"ind":"Subject, linking verb, complement.","word":" They eat bread","correct":"Eles comem pão","choices":["Eles comem pão","Eles bebem água","Eles assistem filmes","Eles escrevem cartas"],"hint":"Sujeito + verbo + objeto direto","example":"They eat bread."},
  {"ind":"Subject, linking verb, complement.","word":" I watch movies","correct":"Eu assisto filmes","choices":["Eu assisto filmes","Eu leio livros","Eu bebo água","Eu corro rápido"],"hint":"Sujeito + verbo + objeto direto","example":"I watch movies."},
  {"ind":"Subject, linking verb, complement.","word":" She cooks dinner","correct":"Ela cozinha o jantar","choices":["Ela cozinha o jantar","Ela bebe suco","Ela lê revistas","Ela canta músicas"],"hint":"Sujeito + verbo + objeto direto","example":"She cooks dinner."},
  {"ind":"Subject, linking verb, complement.","word":" He drinks tea","correct":"Ele bebe chá","choices":["Ele bebe chá","Ele lê jornais","Ele joga futebol","Ele escreve cartas"],"hint":"Sujeito + verbo + objeto direto","example":"He drinks tea."},
  {"ind":"Subject, linking verb, complement.","word":" We read books","correct":"Nós lemos livros","choices":["Nós lemos livros","Nós jogamos futebol","Nós bebemos água","Nós assistimos TV"],"hint":"Sujeito + verbo + objeto direto","example":"We read books."},
  {"ind":"Subject, linking verb, complement.","word":" They write emails","correct":"Eles escrevem emails","choices":["Eles escrevem emails","Eles bebem leite","Eles jogam cartas","Eles leem jornais"],"hint":"Sujeito + verbo + objeto direto","example":"They write emails."},
  {"ind":"Subject, linking verb, complement.","word":" I run fast","correct":"Eu corro rápido","choices":["Eu corro rápido","Eu canto músicas","Eu leio livros","Eu assisto TV"],"hint":"Sujeito + verbo + advérbio","example":"I run fast."},
  {"ind":"Subject, linking verb, complement.","word":" She sings songs","correct":"Ela canta músicas","choices":["Ela canta músicas","Ela escreve cartas","Ela joga futebol","Ela bebe água"],"hint":"Sujeito + verbo + objeto direto","example":"She sings songs."},
  {"ind":"Subject, linking verb, complement.","word":" He drives a car","correct":"Ele dirige um carro","choices":["Ele dirige um carro","Ele lê livros","Ele assiste TV","Ele joga futebol"],"hint":"Sujeito + verbo + objeto direto","example":"He drives a car."},
  {"ind":"Subject, linking verb, complement.","word":" We eat pizza","correct":"Nós comemos pizza","choices":["Nós comemos pizza","Nós bebemos leite","Nós jogamos cartas","Nós lemos livros"],"hint":"Sujeito + verbo + objeto direto","example":"We eat pizza."},
  {"ind":"Subject, linking verb, complement.","word":" They play football","correct":"Eles jogam futebol","choices":["Eles jogam futebol","Eles leem jornais","Eles bebem chá","Eles escrevem cartas"],"hint":"Sujeito + verbo + objeto direto","example":"They play football."},
  {"ind":"Subject, linking verb, complement.","word":" I drink juice","correct":"Eu bebo suco","choices":["Eu bebo suco","Eu como pão","Eu leio livros","Eu assisto TV"],"hint":"Sujeito + verbo + objeto direto","example":"I drink juice. → Eu bebo suco."},
  {"ind":"Subject, linking verb, complement.","word":" She goes to school","correct":"Ela vai para a escola","choices":["Ela vai para a escola","Ela lê livros","Ela bebe água","Ela joga futebol"],"hint":"Sujeito + verbo + complemento de lugar","example":"She goes to school."},
  {"ind":"Subject, linking verb, complement.","word":" He studies English","correct":"Ele estuda inglês","choices":["Ele estuda inglês","Ele joga futebol","Ele bebe água","Ele lê livros"],"hint":"Sujeito + verbo + objeto direto","example":"He studies English."},
  {"ind":"Subject, linking verb, complement.","word":" We watch TV","correct":"Nós assistimos TV","choices":["Nós assistimos TV","Nós bebemos água","Nós jogamos cartas","Nós lemos livros"],"hint":"Sujeito + verbo + objeto direto","example":"We watch TV."},


	{"ind":"Encontre frase","word":"The book is on the table.","correct":"O livro está sobre a mesa.","choices":["O livro está no meu bolso.","Eu tenho o livro.","O livro está sobre a mesa.","Livro muito bom"],"hint":"Livro Mesa","example":"Alguém informando algo"},
	{"ind":"Encontre frase","word":"The book is on the table.","correct":"O livro está sobre a mesa.","choices":["O livro está no meu bolso.","Eu tenho o livro.","O livro está sobre a mesa.","Livro muito bom"],"hint":"Livro Mesa","example":"Alguém informando algo"},
	{"ind":"Encontre frase","word":"The cat is under the chair.","correct":"O gato está debaixo da cadeira.","choices":["O gato está na mesa.","O gato está debaixo da cadeira.","Eu gosto do gato.","A cadeira é nova"],"hint":"Gato Cadeira","example":"Descrição de lugar"},
	{"ind":"Encontre frase","word":"The pen is in the bag.","correct":"A caneta está na bolsa.","choices":["A bolsa é grande.","A caneta está na bolsa.","Eu perdi a caneta.","A caneta é azul"],"hint":"Caneta Bolsa","example":"Informação simples"},
	{"ind":"Encontre frase","word":"The phone is on the bed.","correct":"O telefone está na cama.","choices":["O telefone está no bolso.","A cama é confortável.","O telefone está na cama.","Eu uso telefone"],"hint":"Telefone Cama","example":"Descrição"},
	{"ind":"Encontre frase","word":"The keys are on the desk.","correct":"As chaves estão sobre a mesa.","choices":["A mesa é limpa.","As chaves estão no carro.","As chaves estão sobre a mesa.","Eu perdi as chaves"],"hint":"Chaves Mesa","example":"Aviso"},
	{"ind":"Encontre frase","word":"The dog is in the yard.","correct":"O cachorro está no quintal.","choices":["O cachorro está no quintal.","O quintal é grande.","Eu gosto de cachorro.","O cachorro corre"],"hint":"Cachorro Quintal","example":"Localização"},
	{"ind":"Encontre frase","word":"The milk is in the fridge.","correct":"O leite está na geladeira.","choices":["O leite está quente.","A geladeira é nova.","O leite está na geladeira.","Eu bebo leite"],"hint":"Leite Geladeira","example":"Rotina"},
	{"ind":"Encontre frase","word":"The shoes are under the bed.","correct":"Os sapatos estão debaixo da cama.","choices":["Os sapatos são novos.","A cama é grande.","Os sapatos estão debaixo da cama.","Eu comprei sapatos"],"hint":"Sapatos Cama","example":"Organização"},
	{"ind":"Encontre frase","word":"The car is in the garage.","correct":"O carro está na garagem.","choices":["A garagem é pequena.","O carro está na rua.","O carro está na garagem.","Eu dirijo o carro"],"hint":"Carro Garagem","example":"Informação"},
	{"ind":"Encontre frase","word":"The cup is on the counter.","correct":"A xícara está no balcão.","choices":["A xícara é branca.","O balcão é alto.","A xícara está no balcão.","Eu quebrei a xícara"],"hint":"Xícara Balcão","example":"Cozinha"},
	{"ind":"Encontre frase","word":"The teacher is in the classroom.","correct":"O professor está na sala de aula.","choices":["A sala é grande.","O professor ensina bem.","O professor está na sala de aula.","Eu gosto do professor"],"hint":"Professor Sala","example":"Escola"},
	{"ind":"Encontre frase","word":"The students are in the library.","correct":"Os alunos estão na biblioteca.","choices":["A biblioteca é silenciosa.","Os alunos estudam.","Os alunos estão na biblioteca.","Eu sou aluno"],"hint":"Alunos Biblioteca","example":"Estudo"},
	{"ind":"Encontre frase","word":"The clock is on the wall.","correct":"O relógio está na parede.","choices":["A parede é branca.","O relógio é antigo.","O relógio está na parede.","Eu tenho relógio"],"hint":"Relógio Parede","example":"Descrição"},
	{"ind":"Encontre frase","word":"The food is on the plate.","correct":"A comida está no prato.","choices":["O prato é grande.","A comida está quente.","A comida está no prato.","Eu gosto de comida"],"hint":"Comida Prato","example":"Refeição"},
	{"ind":"Encontre frase","word":"The child is in the room.","correct":"A criança está no quarto.","choices":["O quarto é azul.","A criança dorme.","A criança está no quarto.","Eu vejo a criança"],"hint":"Criança Quarto","example":"Família"},
	{"ind":"Encontre frase","word":"The ball is under the table.","correct":"A bola está debaixo da mesa.","choices":["A mesa é redonda.","A bola é vermelha.","A bola está debaixo da mesa.","Eu chutei a bola"],"hint":"Bola Mesa","example":"Brincadeira"},
	{"ind":"Encontre frase","word":"The bus is at the stop.","correct":"O ônibus está no ponto.","choices":["O ponto é longe.","O ônibus está atrasado.","O ônibus está no ponto.","Eu pego ônibus"],"hint":"Ônibus Ponto","example":"Transporte"},
	{"ind":"Encontre frase","word":"The computer is on the desk.","correct":"O computador está na mesa.","choices":["O computador é novo.","A mesa é limpa.","O computador está na mesa.","Eu uso computador"],"hint":"Computador Mesa","example":"Trabalho"},
	{"ind":"Encontre frase","word":"The store is on the corner.","correct":"A loja fica na esquina.","choices":["A esquina é movimentada.","A loja é grande.","A loja fica na esquina.","Eu gosto da loja"],"hint":"Loja Esquina","example":"Cidade"},
	{"ind":"Encontre frase","word":"The baby is in the crib.","correct":"O bebê está no berço.","choices":["O berço é branco.","O bebê dorme.","O bebê está no berço.","Eu vejo o bebê"],"hint":"Bebê Berço","example":"Casa"},
	{"ind":"Encontre frase","word":"The picture is on the shelf.","correct":"O quadro está na prateleira.","choices":["A prateleira é alta.","O quadro é bonito.","O quadro está na prateleira.","Eu pintei o quadro"],"hint":"Quadro Prateleira","example":"Decoração"},
	{"ind":"Encontre frase","word":"The money is in the wallet.","correct":"O dinheiro está na carteira.","choices":["A carteira é preta.","Eu perdi dinheiro.","O dinheiro está na carteira.","Eu usei a carteira"],"hint":"Dinheiro Carteira","example":"Aviso"},
	{"ind":"Encontre frase","word":"The bird is in the tree.","correct":"O pássaro está na árvore.","choices":["A árvore é alta.","O pássaro canta.","O pássaro está na árvore.","Eu vi o pássaro"],"hint":"Pássaro Árvore","example":"Natureza"},
	{"ind":"Encontre frase","word":"The lamp is on the table.","correct":"A lâmpada está sobre a mesa.","choices":["A mesa é pequena.","A lâmpada é forte.","A lâmpada está sobre a mesa.","Eu liguei a lâmpada"],"hint":"Lâmpada Mesa","example":"Iluminação"},
	{"ind":"Encontre frase","word":"The clothes are in the closet.","correct":"As roupas estão no armário.","choices":["O armário é grande.","As roupas são novas.","As roupas estão no armário.","Eu lavei roupas"],"hint":"Roupas Armário","example":"Organização"},
	{"ind":"Encontre frase","word":"The sandwich is on the plate.","correct":"O sanduíche está no prato.","choices":["O prato é branco.","O sanduíche é bom.","O sanduíche está no prato.","Eu comi sanduíche"],"hint":"Sanduíche Prato","example":"Lanche"},
	{"ind":"Encontre frase","word":"The letter is in the envelope.","correct":"A carta está no envelope.","choices":["O envelope é branco.","A carta é longa.","A carta está no envelope.","Eu escrevi a carta"],"hint":"Carta Envelope","example":"Correio"},
	{"ind":"Encontre frase","word":"The shoes are by the door.","correct":"Os sapatos estão perto da porta.","choices":["A porta está aberta.","Os sapatos são caros.","Os sapatos estão perto da porta.","Eu limpei os sapatos"],"hint":"Sapatos Porta","example":"Casa"},
	{"ind":"Encontre frase","word":"The chair is next to the table.","correct":"A cadeira está ao lado da mesa.","choices":["A mesa é nova.","A cadeira é confortável.","A cadeira está ao lado da mesa.","Eu sentei na cadeira"],"hint":"Cadeira Mesa","example":"Descrição"},
	{"ind":"Encontre frase","word":"The children are in the park.","correct":"As crianças estão no parque.","choices":["O parque é bonito.","As crianças brincam.","As crianças estão no parque.","Eu fui ao parque"],"hint":"Crianças Parque","example":"Lazer"},
	{"ind":"Encontre frase","word":"The phone is in my pocket.","correct":"O telefone está no meu bolso.","choices":["Meu bolso é pequeno.","O telefone é novo.","O telefone está no meu bolso.","Eu uso telefone"],"hint":"Telefone Bolso","example":"Cotidiano"},
	{"ind":"Encontre frase","word":"The water is in the glass.","correct":"A água está no copo.","choices":["O copo é grande.","A água é fria.","A água está no copo.","Eu bebo água"],"hint":"Água Copo","example":"Rotina"},
	{"ind":"Encontre frase","word":"The train is at the station.","correct":"O trem está na estação.","choices":["A estação é antiga.","O trem é rápido.","O trem está na estação.","Eu peguei o trem"],"hint":"Trem Estação","example":"Viagem"},
	{"ind":"Encontre frase","word":"The flowers are in the vase.","correct":"As flores estão no vaso.","choices":["O vaso é bonito.","As flores são coloridas.","As flores estão no vaso.","Eu comprei flores"],"hint":"Flores Vaso","example":"Decoração"},
	{"ind":"Encontre frase","word":"The notebook is in the backpack.","correct":"O caderno está na mochila.","choices":["A mochila é pesada.","O caderno é novo.","O caderno está na mochila.","Eu escrevo no caderno"],"hint":"Caderno Mochila","example":"Escola"},
	{"ind":"Encontre frase","word":"The television is in the living room.","correct":"A televisão está na sala.","choices":["A sala é grande.","A televisão é nova.","A televisão está na sala.","Eu assisto televisão"],"hint":"TV Sala","example":"Casa"},
	{"ind":"Encontre frase","word":"The cake is in the oven.","correct":"O bolo está no forno.","choices":["O forno está quente.","O bolo é doce.","O bolo está no forno.","Eu fiz o bolo"],"hint":"Bolo Forno","example":"Cozinha"},
	{"ind":"Encontre frase","word":"The bike is in the yard.","correct":"A bicicleta está no quintal.","choices":["O quintal é grande.","A bicicleta é nova.","A bicicleta está no quintal.","Eu ando de bicicleta"],"hint":"Bicicleta Quintal","example":"Casa"},
	{"ind":"Encontre frase","word":"The hat is on the chair.","correct":"O chapéu está na cadeira.","choices":["A cadeira é velha.","O chapéu é preto.","O chapéu está na cadeira.","Eu uso chapéu"],"hint":"Chapéu Cadeira","example":"Descrição"},
	{"ind":"Encontre frase","word":"The soap is in the bathroom.","correct":"O sabonete está no banheiro.","choices":["O banheiro é limpo.","O sabonete é cheiroso.","O sabonete está no banheiro.","Eu lavei as mãos"],"hint":"Sabonete Banheiro","example":"Higiene"},
	{"ind":"Encontre frase","word":"The bag is under the desk.","correct":"A bolsa está debaixo da mesa.","choices":["A mesa é grande.","A bolsa é pesada.","A bolsa está debaixo da mesa.","Eu perdi a bolsa"],"hint":"Bolsa Mesa","example":"Localização"},
	{"ind":"Encontre frase","word":"The doctor is in the office.","correct":"O médico está no consultório.","choices":["O consultório é limpo.","O médico ajuda.","O médico está no consultório.","Eu vi o médico"],"hint":"Médico Consultório","example":"Saúde"},
	{"ind":"Encontre frase","word":"The papers are on the floor.","correct":"Os papéis estão no chão.","choices":["O chão está sujo.","Os papéis são importantes.","Os papéis estão no chão.","Eu peguei os papéis"],"hint":"Papéis Chão","example":"Aviso"},
	{"ind":"Encontre frase","word":"The family is at home.","correct":"A família está em casa.","choices":["A casa é grande.","A família janta.","A família está em casa.","Eu amo minha família"],"hint":"Família Casa","example":"Cotidiano"},
	{"ind":"Encontre frase","word":"The teacher is at the door.","correct":"O professor está na porta.","choices":["A porta está aberta.","O professor chegou.","O professor está na porta.","Eu vi o professor"],"hint":"Professor Porta","example":"Escola"},
	{"ind":"Encontre frase","word":"The coffee is on the table.","correct":"O café está na mesa.","choices":["A mesa é pequena.","O café está quente.","O café está na mesa.","Eu gosto de café"],"hint":"Café Mesa","example":"Café servido"},


	{"ind":"Complete a palavra","word":"h_llo","correct":"hello","choices":["hello","hallo","hullo","hill"],"hint":"Cumprimento em inglês","example":"Hello, how are you?"},
	{"ind":"Complete a palavra","word":"b_ok","correct":"book","choices":["book","back","bake","bank"],"hint":"Objeto para ler","example":"I read a book."},
	{"ind":"Complete a palavra","word":"c_t","correct":"cat","choices":["cat","cut","cot","cap"],"hint":"Animal que mia","example":"The cat is black."},
	{"ind":"Complete a palavra","word":"d_g","correct":"dog","choices":["dig","dog","dug","dag"],"hint":"Animal que late","example":"My dog is friendly."},
	{"ind":"Complete a palavra","word":"h_us_","correct":"house","choices":["horse","house","hose","hours"],"hint":"Lugar onde se mora","example":"My house is big."},
	{"ind":"Complete a palavra","word":"w_t_r","correct":"water","choices":["winter","water","waiter","writer"],"hint":"Bebida essencial","example":"I drink water."},
	{"ind":"Complete a palavra","word":"m_lk","correct":"milk","choices":["milk","meal","mill","mask"],"hint":"Bebida branca","example":"Milk is healthy."},
	{"ind":"Complete a palavra","word":"c_r","correct":"car","choices":["car","cat","cap","can"],"hint":"Veículo","example":"I have a car."},
	{"ind":"Complete a palavra","word":"b_d","correct":"bed","choices":["bad","bed","bid","bud"],"hint":"Lugar para dormir","example":"The bed is soft."},
	{"ind":"Complete a palavra","word":"t_bl_","correct":"table","choices":["title","table","cable","stable"],"hint":"Móvel","example":"The book is on the table."},
	{"ind":"Complete a palavra","word":"ch_i_","correct":"chair","choices":["chain","chair","cheap","cheat"],"hint":"Lugar para sentar","example":"Sit on the chair."},
	{"ind":"Complete a palavra","word":"w_nd_w","correct":"window","choices":["widow","window","shadow","windy"],"hint":"Entrada de luz","example":"Open the window."},
	{"ind":"Complete a palavra","word":"d_o_","correct":"door","choices":["doom","door","deer","down"],"hint":"Entrada da casa","example":"Close the door."},
	{"ind":"Complete a palavra","word":"s_h__l","correct":"school","choices":["school","schedule","scholar","shovel"],"hint":"Lugar de estudar","example":"I go to school."},
	{"ind":"Complete a palavra","word":"t__ch_r","correct":"teacher","choices":["teacher","toucher","talker","thinker"],"hint":"Pessoa que ensina","example":"The teacher is kind."},
	{"ind":"Complete a palavra","word":"b_y","correct":"boy","choices":["bay","buy","boy","box"],"hint":"Criança do sexo masculino","example":"The boy is happy."},
	{"ind":"Complete a palavra","word":"g_rl","correct":"girl","choices":["grill","girl","goal","glow"],"hint":"Criança do sexo feminino","example":"The girl is smart."},
	{"ind":"Complete a palavra","word":"f__d","correct":"food","choices":["fold","food","flood","foot"],"hint":"O que se come","example":"The food is ready."},
	{"ind":"Complete a palavra","word":"c_ff_e","correct":"coffee","choices":["coffee","toffee","office","copper"],"hint":"Bebida quente","example":"I drink coffee."},
	{"ind":"Complete a palavra","word":"t__","correct":"tea","choices":["tea","two","toe","ten"],"hint":"Bebida quente","example":"I like tea."},
	{"ind":"Complete a palavra","word":"r_d","correct":"red","choices":["rid","rod","red","rad"],"hint":"Cor","example":"The car is red."},
	{"ind":"Complete a palavra","word":"b_u_","correct":"blue","choices":["blue","blur","black","blame"],"hint":"Cor","example":"The sky is blue."},
	{"ind":"Complete a palavra","word":"g_e_n","correct":"green","choices":["grain","green","grown","ground"],"hint":"Cor","example":"The grass is green."},
	{"ind":"Complete a palavra","word":"b_g","correct":"big","choices":["big","bag","bug","beg"],"hint":"Tamanho grande","example":"The house is big."},
	{"ind":"Complete a palavra","word":"s_all","correct":"small","choices":["small","stall","smell","skill"],"hint":"Tamanho pequeno","example":"The dog is small."},
	{"ind":"Complete a palavra","word":"f_st","correct":"fast","choices":["fast","fact","fist","fish"],"hint":"Rápido","example":"The car is fast."},
	{"ind":"Complete a palavra","word":"s_o_","correct":"slow","choices":["snow","slow","show","slot"],"hint":"Devagar","example":"The turtle is slow."},
	{"ind":"Complete a palavra","word":"h_ppy","correct":"happy","choices":["happy","hobby","hippy","harpy"],"hint":"Sentimento positivo","example":"I am happy."},
	{"ind":"Complete a palavra","word":"s_d","correct":"sad","choices":["sad","set","sit","sun"],"hint":"Sentimento negativo","example":"He is sad."},
	{"ind":"Complete a palavra","word":"t_r_d","correct":"tired","choices":["tired","tried","trend","train"],"hint":"Cansado","example":"I am tired."},
	{"ind":"Complete a palavra","word":"r_n","correct":"run","choices":["run","ran","rim","rug"],"hint":"Correr","example":"I run fast."},
	{"ind":"Complete a palavra","word":"w_lk","correct":"walk","choices":["walk","work","week","will"],"hint":"Andar","example":"I walk home."},
	{"ind":"Complete a palavra","word":"e_t","correct":"eat","choices":["eat","ear","end","age"],"hint":"Comer","example":"I eat pizza."},
	{"ind":"Complete a palavra","word":"dr_nk","correct":"drink","choices":["drink","drank","drive","dream"],"hint":"Beber","example":"I drink water."},
	{"ind":"Complete a palavra","word":"s_e_p","correct":"sleep","choices":["sleep","sweep","sheep","slip"],"hint":"Dormir","example":"I sleep early."},
	{"ind":"Complete a palavra","word":"r__d","correct":"read","choices":["road","read","raid","real"],"hint":"Ler","example":"I read books."},
	{"ind":"Complete a palavra","word":"wr_te","correct":"write","choices":["write","wrong","wrote","white"],"hint":"Escrever","example":"I write emails."},
	{"ind":"Complete a palavra","word":"l__k","correct":"look","choices":["lock","luck","look","leak"],"hint":"Olhar","example":"Look at me."},
	{"ind":"Complete a palavra","word":"l_st_n","correct":"listen","choices":["listen","lesson","little","latest"],"hint":"Ouvir com atenção","example":"Listen to me."},
	{"ind":"Complete a palavra","word":"s__k","correct":"speak","choices":["sneak","speak","spook","stack"],"hint":"Falar","example":"I speak English."},
	{"ind":"Complete a palavra","word":"f__e","correct":"face","choices":["face","fact","fade","fake"],"hint":"Parte do corpo","example":"She has a happy face."},
	{"ind":"Complete a palavra","word":"h__d","correct":"hand","choices":["hard","hand","head","hold"],"hint":"Parte do corpo","example":"Wash your hands."},
	{"ind":"Complete a palavra","word":"l_g","correct":"leg","choices":["leg","log","lag","let"],"hint":"Parte do corpo","example":"My leg hurts."},
	{"ind":"Complete a palavra","word":"f__t","correct":"foot","choices":["food","foot","feel","fast"],"hint":"Parte do corpo","example":"My foot is tired."},
	{"ind":"Complete a palavra","word":"h__r","correct":"hair","choices":["hair","hear","hard","harm"],"hint":"Cabelo","example":"Her hair is long."},
	{"ind":"Complete a palavra","word":"s_n","correct":"sun","choices":["sun","son","sin","run"],"hint":"Estrela do dia","example":"The sun is bright."},
	{"ind":"Complete a palavra","word":"m__n","correct":"moon","choices":["moon","mean","man","main"],"hint":"Satélite natural","example":"The moon is full."},
	{"ind":"Complete a palavra","word":"s_y","correct":"sky","choices":["say","sky","shy","spy"],"hint":"Céu","example":"The sky is blue."},
	{"ind":"Complete a palavra","word":"s__r","correct":"star","choices":["star","store","stir","step"],"hint":"Estrela","example":"I see a star."},
	{"ind":"Complete a palavra","word":"r__n","correct":"rain","choices":["rain","road","ring","ruin"],"hint":"Chuva","example":"The rain is strong."},
	{"ind":"Complete a palavra","word":"b_r_d","correct":"bread","choices":["bread","brand","broad","break"],"hint":"Alimento","example":"I eat bread."},
	{"ind":"Complete a palavra","word":"c_k_","correct":"cake","choices":["cake","cook","coke","care"],"hint":"Doce","example":"The cake is good."},
	{"ind":"Complete a palavra","word":"r_c_","correct":"rice","choices":["rice","race","rich","ride"],"hint":"Comida","example":"Rice and beans."},
	{"ind":"Complete a palavra","word":"f__t","correct":"fruit","choices":["fruit","front","frost","first"],"hint":"Alimento natural","example":"Fruit is healthy."},
	{"ind":"Complete a palavra","word":"c__s_","correct":"cheese","choices":["cheese","choose","chance","chase"],"hint":"Derivado do leite","example":"I like cheese."},
	{"ind":"Complete a palavra","word":"s__e","correct":"shoe","choices":["shoe","show","shot","shut"],"hint":"Calçado","example":"My shoe is new."},
	{"ind":"Complete a palavra","word":"s__t","correct":"shirt","choices":["shirt","short","skirt","sport"],"hint":"Roupa","example":"The shirt is clean."},
	{"ind":"Complete a palavra","word":"p__t","correct":"pants","choices":["pants","points","prints","plants"],"hint":"Roupa","example":"My pants are blue."},
	{"ind":"Complete a palavra","word":"c__t","correct":"coat","choices":["coat","cost","cast","cute"],"hint":"Roupa de frio","example":"Wear a coat."},
	{"ind":"Complete a palavra","word":"h__","correct":"hat","choices":["hat","hot","hit","hut"],"hint":"Acessório","example":"The hat is black."},
	{"ind":"Complete a palavra","word":"c__k","correct":"clock","choices":["clock","click","clerk","cloak"],"hint":"Mostra as horas","example":"The clock is old."},
	{"ind":"Complete a palavra","word":"p__n","correct":"phone","choices":["phone","photo","phony","phase"],"hint":"Dispositivo","example":"My phone rings."},
	{"ind":"Complete a palavra","word":"c__p","correct":"cup","choices":["cup","cap","cop","cut"],"hint":"Recipiente","example":"A cup of tea."},
	{"ind":"Complete a palavra","word":"p__e","correct":"plate","choices":["plate","place","plane","plant"],"hint":"Usado para comer","example":"The plate is clean."},
	{"ind":"Complete a palavra","word":"k__e","correct":"knife","choices":["knife","kneel","known","knock"],"hint":"Utensílio","example":"Use a knife."},
	{"ind":"Complete a palavra","word":"s__t","correct":"seat","choices":["seat","set","sit","sent"],"hint":"Assento","example":"Take a seat."},
	{"ind":"Complete a palavra","word":"r__m","correct":"room","choices":["room","roam","read","root"],"hint":"Cômodo","example":"My room is small."},
	{"ind":"Complete a palavra","word":"b__h","correct":"bath","choices":["bath","both","belt","bank"],"hint":"Banho","example":"Take a bath."},
	{"ind":"Complete a palavra","word":"k__c_n","correct":"kitchen","choices":["kitchen","chicken","kitten","kingdom"],"hint":"Lugar de cozinhar","example":"The kitchen is clean."},
	{"ind":"Complete a palavra","word":"g__d_n","correct":"garden","choices":["garden","golden","ground","gordon"],"hint":"Área externa","example":"The garden is green."},
	{"ind":"Complete a palavra","word":"h__p","correct":"help","choices":["help","hold","hope","heap"],"hint":"Ajudar","example":"Help me, please."},
	{"ind":"Complete a palavra","word":"l__e","correct":"love","choices":["love","live","lose","load"],"hint":"Sentimento","example":"I love music."},
	{"ind":"Complete a palavra","word":"h__e","correct":"hope","choices":["hope","home","hole","hate"],"hint":"Esperança","example":"I hope so."},
	{"ind":"Complete a palavra","word":"s__e","correct":"smile","choices":["smile","simple","smell","small"],"hint":"Expressão","example":"She has a smile."},
	{"ind":"Complete a palavra","word":"l__gh","correct":"laugh","choices":["laugh","large","light","length"],"hint":"Rir","example":"They laugh a lot."},
	];


const wordEl = document.getElementById("word");
const optionsEl = document.getElementById("options");
const feedbackEl = document.getElementById("feedback");

let player = null;


// Blogger-safe export ensured
